apiVersion : apps/v1
kind: Deployment
metadata:
  name: sb 
  namespace: default 
  labels:
    app: sb 
spec:
  selector:
    matchLabels:
      app: sb 
  template:
    metadata:
      labels:
        app: sb 
    spec:
      containers:
        - image: mohanayalamanchi251/keda-container
          name: keda-container
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
